"""empty message

Revision ID: 732e9afe284c
Revises: 0487b50912fd
Create Date: 2021-12-11 10:10:45.373769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732e9afe284c'
down_revision = '0487b50912fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
